accounts:
  - name: alice
    coins: ["2000000token"]
  - name: bob
    coins: ["1000000token"]
validator:
  name: alice
  staked: "1000000token"
client:
  vuex:
    path: "vue/src/store"
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: bob
  coins: ["5token"]
  coins_max: ["20token"]
genesis:
  # chain_id: "reex"
  app_state:
    staking:
      params:
        bond_denom: "token"
  consensus_params:
    block:
      max_bytes: "150000"
      max_gas: "1500000"
    evidence:
      max_bytes: "150000"
  crisis:
    constant_fee:
      amount: "1000",
      denom: "token"
  gov:
    deposit_params:
      min_deposit: [ {amount: "10000000", denom: "token"} ]
  mint:
    params:
      mint_denom: "token"

