accounts:
  - name: dev1
    coins: ["100000000000000reex"]
  - name: dev2
    coins: ["100000000000000reex"]
validator:
  name: dev1
  staked: "50000000000000reex"
client:
  vuex:
    path: "vue/src/store"
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: dev2
  coins: ["1000000reex"]
  # coins_max: ["20000000reex"]
genesis:
  # chain_id: "reex"
  app_state:
    staking:
      params:
        bond_denom: "reex"
  consensus_params:
    block:
      max_bytes: "150000"
      max_gas: "1500000"
    evidence:
      max_bytes: "150000"
  crisis:
    constant_fee:
      amount: "1000",
      denom: "reex"
  gov:
    deposit_params:
      min_deposit: [ {amount: "10000000", denom: "reex"} ]
  mint:
    params:
      mint_denom: "reex"

